### ISSUE TITLE
Missing Session 5 and 7

### ISSUE THREAD

**Issue by AarushJ** [Cyber-Labs/Session-Reports#13]
Please get added the Sessions 5 and 7 @sanketsingh24

**Comment by sanketsingh24** [comment]
Session 5 was to be done by nikhil.

**Comment by AarushJ** [comment]
and session 7?

**Comment by AarushJ** [comment]
@sanketsingh24  session 7?

**Comment by sanketsingh24** [comment]
@AarushJ Sessions has been numbered wrongly. There was no session on 1/2/19, but [Session 6](https://github.com/Cyber-Labs/Session-Reports/blob/master/Web%20Development/Session_6.md) has a date of 31/01 and [Session 8](https://github.com/Cyber-Labs/Session-Reports/blob/master/Web%20Development/session_8.md) has a date of 02/02, so Session 8 should be session 7.

**Comment by sanketsingh24** [comment]
Also, session 4 has a date of 30/01 but it should be 29/01 as Session 5 was on 30/01

**Comment by ShridharGoel** [comment]
This has been fixed I think. Can we close this?

**Comment by sanketsingh24** [comment]
No, session 5 is still missing, we will close this after it is added
